### ISSUE TITLE
FatFS Initialization unsuccessful

### ISSUE THREAD

**Issue by karthik-k-bhat** [PolyVinalDistillate/NSDSPI#2]
Hey Nick!

I found your project through Cypress Community and StackOverflow answers. This is exactly what I needed for my project as well.

However, I am facing an issue with the FATFS initialization (i.e., with the disk_initialization() function). The function is returning 0x01, which means "STA_NOINIT" flag is set. And also, all the following functions are also returning an error.
Can you help me out? 

Thanks in advance!
Karthik Bhat

**Comment by PolyVinalDistillate** [comment]
Been quite some time sincve I looked at this! But I'm assuming you have corrected your problem?
Cheers,
Nick.
